### ISSUE TITLE
What is Spotnik?

### ISSUE THREAD

**Issue by W4JEW** [armel/RRFVoice#7]
Would it be possible for you to include a reference URL that provides more information on what Spotnik is?

Merci beaucoup!

**Comment by armel** [comment]
Hi,

A Spotnik is an FM hotspot that allows you to connect to a French Repeater Network (RRF Réseau des Répéteurs Francophone). It works with SVXLink and SVXReflector. 

More about the RRF on this video by Pascal VA2PV https://www.youtube.com/watch?v=bCGkSUbdjm8&list=PLIrScA_-O7cxXtDncyFmRnq5AIbVrqHmp

73'

Armel F4HWN

**Comment by W4JEW** [comment]
Ahh - OK. That's excellent!

I just installed your IC705SMeter code on an M5Stack Basic that I bought yesterday. I'm looking at the IC705MultiMeter repository now.

Merci!
